spring:
  application:
    name: planning-service

server:
  port: 8084

services:
  flight:
    url: ${SERVICES_FLIGHT_URL:http://localhost:8082}
  hotel:
    url: ${SERVICES_HOTEL_URL:http://localhost:8083}
